# Generated by Django 3.2.18 on 2024-07-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_classified', '0004_auto_20240712_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
