# Generated by Django 3.2.18 on 2024-07-12 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_classified', '0007_auto_20240712_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='django_classified.area', verbose_name='area'),
        ),
        migrations.AlterField(
            model_name='area',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
    ]
